### ISSUE TITLE
Can't start emulator on Linux without wine

### ISSUE THREAD

**Issue by bpivaty** [liias/monkey#12]
Hello,

Thank you for this pluggin. I was a bit desperate to be obliged to use eclipse.

Everything went just fine, setting was easy, build OK but fails with the following insult: 

Error running 'test': Cannot run program "wine" (in directory "/opt/sdk/connectiq-sdk/bin"): error=2, No such file or directory

I am surprised to read wine here.
Any suggestion?

Bertrand

**Comment by bpivaty** [comment]
Hey, thank you for the reply. But does that mean that I can't use this plugin with the native emulator?

**Comment by liias** [comment]
On Linux, no. Not hard to fix though if you're interested. Just clone the repo and let gradle do its magic and then search for wine from source code. I don't have Linux currently installed and not enough time atm.

**Comment by bpivaty** [comment]
To be honest this was already my intention :)
Thank you :)
