### ISSUE TITLE
Error running app.  Can't connect to simulatorHelper

### ISSUE THREAD

**Issue by portcitycreations** [liias/monkey#2]
Having fired up a new project with no changes, trying to run the watch application give this error...

Error running <appName>: Could not connect to simulatorHelper

The simulator pops up, but nothing else happens, and the above message appears in the event log.

**Comment by liias** [comment]
Does running an app work in the official Eclipse plugin?

**Comment by portcitycreations** [comment]
Haven't used the eclipse plugin.  I can run it via the command line with 'monkeydo'.  Do I need to fill in value for the run config?

**Comment by liias** [comment]
Do you still get the error if you keep the simulator running and try to run from IDEA again?

**Comment by enricoschroeder** [comment]
Hey there, same problem here (using current 0.3.2 version of the plugin together with the Connect SDK 2.1.2 or 2.1.3 on OSX 10.11). 

When I hit "run", the simulator is starting up as expected, but then I get the same "Could not connect to simulatorHelper" message in IDEA. Everything is working fine using the Eclipse plugin.

**Comment by liias** [comment]
Alright, thanks. Will check it out when I get a chance to use os x. 

Does it also fail if you start simulator beforehand?

**Comment by liias** [comment]
You can try 0.3.2, though I didn't test it.

**Comment by enricoschroeder** [comment]
It's working now, thanks!!

**Comment by liias** [comment]
Great! Also tried on Mac and saw that trying to run again on already running simulator gives some error, but that's some different issue, so will close this one.
