### ISSUE TITLE
Unable to setup SDK with ConnectIQ 2.3.1

### ISSUE THREAD

**Issue by datnguyen87** [liias/monkey#7]
When I select the SDK directory to connect IQ 2.3.1, not thing happen. 
This issue happened on IntelliJ version 2017.1.4, plugin version 0.3.4

**Comment by liias** [comment]
I added a fix for this specific issue in 0.3.4 (need to wait for a day or less usually for the version to appear). Thanks.

I did not test if building/running app with 2.3.1 SDK will actually work though.

**Comment by datnguyen87** [comment]
It works. Thanks!
