### ISSUE TITLE
ModuleProgramRunner

### ISSUE THREAD

**Issue by zolotov** [liias/monkey#8]
Following canRun implementations overrides all other runners and break them. Please reimplement the method or make ModuleProgramRunner the latest runner.

```
return DefaultRunExecutor.EXECUTOR_ID.equals(executorId) && profile instanceof ModuleRunProfile;
```

Relates to https://youtrack.jetbrains.com/issue/GO-5019

**Comment by liias** [comment]
Thanks for reporting, will take a look in a few days.
